# Generated by Django 4.2.9 on 2024-02-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clasificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='Image',
            field=models.ImageField(upload_to='./static'),
        ),
    ]
